EXPLAIN SELECT FIRSTNAME, LASTNAME FROM READERS WHERE FIRSTNAME = 'JOHN';
EXPLAIN SELECT * FROM BOOKS WHERE TITLE = 'The Stranger';

CREATE INDEX IDX_READERS_NAME_LASTNAME ON READERS (FIRSTNAME, LASTNAME);
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);

EXPLAIN SELECT FIRSTNAME, LASTNAME FROM READERS WHERE FIRSTNAME = 'JOHN';
EXPLAIN SELECT * FROM BOOKS WHERE TITLE = 'The Stranger';

